server {
    listen 80;

    # Telling the browser to be stricter when handling content
    add_header X-Frame-Option "SAMEORIGIN";
    #
    add_header X-Content-Type-Options "nosniff"; 

    location /health {
        access_log off;
        return 200 '{"status":"ok"}';
        add_header Content-Type application/json;
}

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}